name: mobmongo
description: A new flutter plugin project.
version: 0.0.9
homepage: https://github.com/malengatiger/flutter-mongdb-mobile

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  plugin:
    platforms:
      android:
        package: com.aftarobot.mobmongo
        pluginClass: Mobmongo3Plugin


